export const phases = [
  {
    id: "phase-1",
    label: "Phase 1",
    title: "Runtime Foundation",
    status: "Complete",
    color: "bg-emerald-500",
    details: [
      "Deterministic runtime loop",
      "RobotState single source of truth",
      "Scheduler + SchedulingPolicy abstraction",
      "EventBus (stateless, immutable events)",
      "Module interface + ExecutionLayer",
      "SimulatedStateEstimator",
      "Full test coverage (63 tests passing)",
    ],
  },
  {
    id: "phase-2a",
    label: "Phase 2A",
    title: "Criticality Scheduling",
    status: "Complete",
    color: "bg-blue-500",
    details: [
      "CriticalityScoringStrategy (safety/mission/urgency/resource)",
      "GreedySelectionStrategy (budget-constrained)",
      "Configurable weights + resource penalties",
      "Validation pipeline: CSV + SVG + Markdown",
      "Sensitivity analysis + ablation framework",
    ],
  },
  {
    id: "phase-2b",
    label: "Phase 2B",
    title: "Risk-Aware Knapsack",
    status: "Complete",
    color: "bg-violet-500",
    details: [
      "Exact 0/1 knapsack (3D DP: compute/time/energy)",
      "Mandatory modules always selected",
      "Deterministic tie-breaking",
      "Pareto-optimal under constraints",
      "~0.3ms decision latency",
    ],
  },
  {
    id: "phase-2c",
    label: "Phase 2C",
    title: "Lexicographic Scheduler",
    status: "Complete",
    color: "bg-amber-500",
    details: [
      "4-level hierarchy: Safety → Mission → Energy → Time",
      "Module graph: deps, redundancy, mutex, shared info",
      "Mandatory ≠ Safety-Critical distinction",
      "Generated scenario suite (20 types, 50+ scenarios)",
      "Ablation study: 8 architectural components",
      "Radar charts, heatmaps, Pareto frontiers",
    ],
  },
];

export const policies = [
  {
    name: "OperatorPriority",
    type: "Baseline",
    description: "Static priority ordering. No resource awareness. Executes all modules.",
    badge: "Priority",
    color: "border-slate-400",
  },
  {
    name: "CriticalityGreedy",
    type: "Adaptive",
    description: "Scores by safety/mission/urgency/resource. Greedy selection by score.",
    badge: "Criticality",
    color: "border-blue-400",
  },
  {
    name: "RiskAwareKnapsack",
    type: "Optimization",
    description: "Exact 0/1 knapsack over compute/time/energy. Mandatory items forced.",
    badge: "Knapsack",
    color: "border-violet-400",
  },
  {
    name: "LexicographicRiskAware",
    type: "Multi-Objective",
    description: "Safety → Mission → Energy → Time. Module graph with deps/mutex/redundancy.",
    badge: "Lexicographic",
    color: "border-amber-400",
  },
];

export const metrics = [
  { value: "< 1ms", label: "Scheduler Latency (P99)", detail: "Lexicographic: 0.5ms avg" },
  { value: "100%", label: "Safety Coverage", detail: "All 20 scenario types" },
  { value: "50+", label: "Generated Scenarios", detail: "Battery, thermal, comms, sensors, actuators" },
  { value: "8", label: "Ablation Components", detail: "Graph, lexicographic, mandatory, safety-critical, classes, redundancy, mutex, shared" },
  { value: "63", label: "Tests Passing", detail: "All phases, deterministic, CI-ready" },
  { value: "0", label: "Runtime Dependencies", detail: "Zero external deps in hot path" },
];

export const scenarios = [
  "Nominal Exploration",
  "Low Battery (5%)",
  "Obstacle Detected",
  "System Emergency",
  "Budget Exhaustion (30%)",
  "Sensor Failure (GPS+Camera)",
  "High Temperature (65°C)",
  "Communication Loss",
  "Navigation Loss (GPS denied)",
  "Camera Degraded",
  "GPS Drift",
  "LIDAR Failure",
  "Deadline Overload",
  "Memory Pressure",
  "Multi-Sensor Failure",
  "Thermal Throttling",
  "Network Partition",
  "Actuator Degradation",
  "Mission Change",
  "Unknown Environment",
];